[package]
name = "day2"
version = "0.1.0"
authors = ["Tomasz Kłak <ext-lux-tk@ad.datcon.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4"
